project_id = "tijsqfupxdyowiticatq"

[functions.update-password-after-security-verification]
verify_jwt = false

[functions.handle-subscription-webhook]
verify_jwt = false

[functions.process-expired-subscriptions]
verify_jwt = false